# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=64)),
                ('eemail', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
