# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eno',
            field=models.CharField(max_length=264),
        ),
    ]
