# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('sname', models.CharField(max_length=64)),
                ('marks', models.IntegerField()),
                ('mob_no', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
