# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mob_no',
            field=models.CharField(max_length=64),
        ),
    ]
